{{- if .Values.meaoMonitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.meaoMonitoring.name }}
  name: {{ .Values.meaoMonitoring.name }}
spec:
  type: {{ .Values.meaoMonitoring.service.type }}
  ports:
    {{ .Values.meaoMonitoring.service.ports | toYaml | nindent 4 }}
  selector:
    app: {{ .Values.meaoMonitoring.name }}
{{- end }}