apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: app-mongo-db-data
  name: app-mongo-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi