apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cfs-portal-claim0
  name: cfs-portal-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
